app:
  title: Scaffolded Backstage Pilot
  baseUrl: http://localhost:7007
  packages: all
  extensions:
    - entity-content:catalog/kubernetes:
        disabled: true

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  cors:
    origin: [http://localhost:7007, http://127.0.0.1:7007]
    methods: [GET, POST, PUT, DELETE, OPTIONS]
    credentials: true
  auth:
    keys:
     - secret: "${BACKEND_SECRET}"

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: postgres

proxy:
  endpoints:
    'argocd/api':
      target: http://argocd-server.argocd.svc.cluster.local/api/v1/
      changeOrigin: true
      secure: false
      allowedHeaders:
        - Authorization
      headers:
        Authorization: "Bearer ${ARGOCD_TOKEN}"

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://kubernetes.default.svc
          name: k3s-cluster
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          id: k3s-pilot

argocd:
  baseUrl: http://argocd-server.argocd.svc.cluster.local
  appLocatorMethods:
    - type: 'config'
      instances:
        - name: main-argo
          url: http://argocd-server.argocd.svc.cluster.local
          token: "${ARGOCD_TOKEN}"
          secure: false

catalog:
  orphanStrategy: delete
  orphanProviderStrategy: delete
  import:
    entityFilename: catalog-info.yaml
  rules:
    - allow: [Component, System, API, Resource, Location, Template, User, Group]

  providers:
    keycloakOrg:
      default:
        baseUrl: http://keycloak-service:8085
        loginRealm: backstage
        realm: backstage
        clientId: backstage-auth
        clientSecret: OMdJB9Phni1MvsqybE0jIaA38UzbOQxHS5i3vtYUvv20hrjLKNgqJ0EFlZBG25SgO5r1uC7L5WtbOfySMekk9z
        schedule:
          frequency: { minutes: 3 }
          timeout: { minutes: 1 }
          initialDelay: { seconds: 15 }

auth:
  environment: development
  session:
    secret: ${BACKEND_SECRET}
  providers:
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

    oidc:
      development:
        clientId: backstage-auth
        clientSecret: OMdJB9Phni1MvsqybE0jIaA38UzbOQxHS5i3vtYUvv20hrjLKNgqJ0EFlZBG25SgO5r1uC7L5WtbOfySMekk9z
        metadataUrl: http://keycloak-service:8085/realms/backstage/.well-known/openid-configuration
        baseUrl: http://keycloak-service:8085
        prompt: auto
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}