app:
  title: Backstage Pilot Deployed
  baseUrl: http://localhost:7007
backend:
  baseUrl: http://localhost:7007
  listen:
    host: 0.0.0.0
    port: 7007
  cors:
    origin: [http://localhost:7007, http://127.0.0.1:7007]
    methods: [GET, POST, PUT, DELETE, OPTIONS]
    credentials: true
  database:
    client: pg
    connection:
      host: backstage-pilot-db-service
      port: 5432
      user: postgres
      password: secret
      database: ""
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Template, User, Group]
  locations:
    - type: file
      target: ./catalog/org-users.yaml
    - type: file
      target: ./catalog/components.yaml
auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
