apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argo-live-service-final
  description: Production service managed via ArgoCD.
  annotations:
    argocd/app-name: argo-live-service-final
    backstage.io/kubernetes-id: argo-live-service-final-deployment
    backstage.io/kubernetes-namespace: default
    backstage.io/kubernetes-label-selector: 'app=argo-live-service-final'
spec:
  type: service
  lifecycle: experimental
  owner: user:default/IvayloB84
