# ==========================================
# STAGE 1: Isolated Production Dependency Resolution
# ==========================================
FROM node:24-trixie-slim AS build

# Install ONLY the package matching the official guide requirements
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev && \
    rm -rf /var/lib/apt/lists/*

RUN corepack enable

USER node
WORKDIR /app
ENV COREPACK_HOME=/tmp/corepack

# 1. Copy core configuration footprints from the host
COPY --chown=node:node backstage.json package.json yarn.lock .yarnrc.yml ./
COPY --chown=node:node .yarn ./.yarn
COPY --chown=node:node .pnp.* ./

# 2. Bring in the production skeleton generated by your host script
COPY --chown=node:node packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

# 3. Focus strictly on production workspaces inside the skeleton.
# This prevents downloading full devDependencies over the network under --no-cache.
RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn workspaces focus --all --production


# ==========================================
# STAGE 2: Lean Production Runtime
# ==========================================
FROM node:24-trixie-slim AS runner

# Install the minimal runtime package for SQLite
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev && \
    rm -rf /var/lib/apt/lists/*

USER node
WORKDIR /app

# Copy the lightweight configuration and core dependency tracking structures
COPY --from=build --chown=node:node /app/.yarn ./.yarn
COPY --from=build --chown=node:node /app/.yarnrc.yml ./
COPY --from=build --chown=node:node /app/backstage.json ./
COPY --from=build --chown=node:node /app/yarn.lock /app/package.json ./

# Copy the production node_modules generated by Yarn in Stage 1
COPY --from=build --chown=node:node /app/node_modules ./node_modules

# Bring in your compiled application code bundle from the host context and extract it
COPY --chown=node:node packages/backend/dist/bundle.tar.gz ./
RUN tar xzf bundle.tar.gz -C ./ && rm bundle.tar.gz

# Runtime configuration settings
ENV NODE_ENV=production
ENV NODE_OPTIONS="--no-node-snapshot"

CMD ["node", "packages/backend", "--config", "/mnt/config-overrides/app-config.yaml"]