apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backstage-manifests/backstage.yaml
  - backstage-manifests/backstage-ingress.yaml
  - backstage-manifests/backstage-pvc.yaml
  - backstage-manifests/keycloak-db-infra.yaml
  - backstage-manifests/keycloak-infrastructure.yaml
  - backstage-manifests/vault-server.yaml
  - backstage-manifests/vault-eso-sync.yaml
  - backstage-manifests/localtunnel-deployment.yaml
configMapGenerator:
  - name: backstage-app-config-cm
    files:
      - app-config.yaml