apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: local-catalog-index
  description: Main index mounting all local cluster pieces cleanly
spec:
  type: file
  targets:
    - ./components.yaml
    - ./org-users.yaml
    - ./github-repo-template.yaml
    - ./dev-test-template.yaml