apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ivaylo.bumbovski
spec:
  profile:
    displayName: Ivaylo Bumbovski
    email: ivaylo.bumbovski@gmail.com
  memberOf: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ivaylob84
spec:
  profile:
    displayName: Ivaylo Bumbovski
    email: ivaylo.bumbovski@gmail.com
  memberOf: []