apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ivaylo.bumbovski  
  namespace: default
spec:
  profile:
    displayName: IvayloB84
    email: ivaylo.bumbovski@gmail.com
  memberOf: [backstage-users]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage-users
  namespace: default
spec:
  type: team
  children: []