apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-pilot
  namespace: default
  labels:
    app: backstage-pilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-pilot
  template:
    metadata:
      labels:
        app: backstage-pilot
    spec:
      serviceAccountName: backstage-cluster-reader
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      hostAliases:
      - ip: "10.43.103.217"
        hostnames:
        - "localhost"
      containers:
      - name: backstage
        image: backstage-pilot:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 7007
        securityContext:
          allowPrivilegeEscalation: false
        command: ["vault", "kv", "run", "-mount=secret", "backstage"]
        args: ["node", "packages/backend", "--config", "app-config.yaml"]
        env:
        - name: VAULT_ADDR
          value: "http://vault-service:8200"
        - name: VAULT_AUTH_METHOD
          value: "kubernetes"
        - name: VAULT_AUTH_ROLE
          value: "backstage-role"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: APP_CONFIG_catalog_orphanStrategy
          value: "delete"
        - name: APP_CONFIG_catalog_processingIntervalSeconds
          value: "300"
        volumeMounts:
        - name: catalog-files-volume
          mountPath: /app/catalog
        - name: main-config-volume
          mountPath: /app/app-config.yaml
          subPath: app-config.yaml
      volumes:
      - name: catalog-files-volume
        configMap:
          name: backstage-local-users-cm
      - name: main-config-volume
        configMap:
          name: backstage-config