apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgres-db
  namespace: default
  labels:
    app: keycloak-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backstage-app-config
                  key: KEYCLOAK_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage-app-config
                  key: KEYCLOAK_DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: backstage-app-config
                  key: KEYCLOAK_DB_NAME
          ports:
            - containerPort: 5432
              name: dbport
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-service
  namespace: default
spec:
  ports:
    - name: tcp
      port: 5433
      targetPort: 5432
      protocol: TCP
  selector:
    app: keycloak-postgres