apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-server
  namespace: default
  labels:
    app: keycloak
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.7.2
          args: ["start-dev", "--http-enabled=true", "--import-realm"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "admin"
            - name: KC_HTTP_PORT
              value: "8085"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://keycloak-postgres-service.default.svc.cluster.local:5433/keycloak_persistence"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backstage-app-config
                  key: KEYCLOAK_DB_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage-app-config
                  key: KEYCLOAK_DB_PASSWORD
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HOSTNAME
              value: "http://localhost:8085"
            - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
              value: "true"
          ports:
            - containerPort: 8085
              name: http
          volumeMounts:
            - name: import-volume
              mountPath: /opt/keycloak/data/import/backstage-realm.json
              subPath: backstage-realm.json
      volumes:
        - name: import-volume
          configMap:
            name: keycloak-drop-in-realm
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: default
  annotations:
    argocd.argoproj.io/sync-policy: Manual
spec:
  ports:
    - name: http
      port: 8085          
      targetPort: 8085   
      protocol: TCP
  selector:
    app: keycloak