apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:18
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backstage-app-config
                  key: KEYCLOAK_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage-app-config
                  key: KEYCLOAK_DB_PASSWORD
            - name: POSTGRES_DB
              value: "keycloak_persistence"
          ports:
            - containerPort: 5432 # Postgres still runs on 5432 inside its own container
              name: dbport
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  namespace: default
spec:
  ports:
    - name: tcp
      port: 5433
      targetPort: 5432      # Routes it to the container's 5432 port
      protocol: TCP
  selector:
    app: postgres-db