apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-permanent-bridge
  namespace: default
spec:
  entryPoints:
    - web  # Automatically listens on your Traefik external entrypoint port
  routes:
  - match: PathPrefix(`/`) # Passes the root path cleanly to satisfy Vault's rigid /ui/ redirects
    kind: Rule
    services:
    - name: vault-service
      port: 8200
