apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-server
  namespace: default
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:latest
        args: ["server", "-dev", "-dev-root-token-id=root-master-token-2026", "-dev-listen-address=0.0.0.0:8200"]
        ports:
        - containerPort: 8200
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 8200
    targetPort: 8200
    nodePort: 30200
  selector:
    app: vault