apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: default
spec:
  provider:
    vault:
      server: "http://vault-service.default.svc.cluster.local:8200"
      version: "v2"
      path: "secret"
      auth:
        tokenSecretRef:
          name: "vault-dev-token"
          key: "root-token"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-app-config
  namespace: default
spec:
  refreshInterval: "15s" 
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: backstage-app-config 
    creationPolicy: Owner
  data:
    - secretKey: KEYCLOAK_CLIENT_ID
      remoteRef:
        key: "backstage"
        property: KEYCLOAK_CLIENT_ID
    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: "backstage"
        property: KEYCLOAK_CLIENT_SECRET
    - secretKey: POSTGRES_USER
      remoteRef:
        key: "backstage"
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: "backstage"
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: "backstage"
        property: POSTGRES_HOST
    - secretKey: BACKEND_SECRET
      remoteRef:
        key: "backstage"
        property: BACKSTAGE_SECRET

