apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-production-config
  namespace: default
data:
  app-config.production.yaml: |
    app:
      title: Backstage Pilot Deployed
      baseUrl: http://localhost:7007
    backend:
      baseUrl: http://localhost:7007
      listen:
        port: 7007
      cors:
        origin: http://localhost:7007
      database:
        client: pg
        connection:
          host: backstage-db-service
          port: 5432
          user: postgres
          password: secret
    auth:
      environment: production
      providers:
        github:
          production:
            clientId: ${AUTH_CLIENT_ID}
            clientSecret: ${AUTH_CLIENT_SECRET}
